// Package fixture is the deterministic synthetic corpus generator of
// doc 10 section 1: Zipf terms, power-law links, degenerate-template
// near-dup clusters, every shape the build and serve gates need that
// real data cannot force on demand.
//
// A corpus is identified by (Version, Seed, N) and every page is a pure
// function of that triple, generated independently per docid, so
// generation streams at any corpus size and parallelizes freely. The
// named artifacts are fixture-v1-10m and fixture-v1-100m, both seed
// 2107; Version bumps whenever any generated byte would change, and the
// golden-hash test pins that discipline.
package fixture

import (
	"crypto/sha256"
	"fmt"
	"math"
	"math/rand"
)

// Version freezes the generator. Any change to generated bytes bumps it
// and renames the artifacts.
const Version = 1

const (
	// fetchBase is the fixed fetch clock; docids are fetch order.
	fetchBase = 1_750_000_000_000

	// Vocabulary shape (doc 05 section 4 arithmetic): a core Zipf
	// vocabulary of N/5 ranks clamped to [200k, 50M], plus ~0.5
	// unique tail ids per doc, lands total terms near the 0.6/doc the
	// spec assumes at 500M docs.
	coreVocabMin = 200_000
	coreVocabMax = 50_000_000

	// zipfS is the Zipf exponent for term ranks; web term frequencies
	// sit near 1.0-1.1 and math/rand's sampler needs s > 1.
	zipfS = 1.07

	// templateShare is the percentage of docs that are members of a
	// degenerate-template near-dup cluster.
	templateShare = 10

	// canonShare is the percentage of non-template docs carrying an
	// explicit rel-canonical to another doc.
	canonShare = 2

	// cjkShare is the percentage of docs whose text is CJK.
	cjkShare = 5
)

// Corpus generates pages for one fixture artifact.
type Corpus struct {
	Seed uint64
	N    uint64

	coreVocab uint64
	templates uint64
	hosts     uint64
}

// New sizes the derived knobs from N.
func New(seed, n uint64) *Corpus {
	c := &Corpus{Seed: seed, N: n}
	c.coreVocab = min(max(n/5, coreVocabMin), coreVocabMax)
	// Template popularity is itself Zipf, so the top template grows a
	// collision run long past the doc 06 10k run-length guard once the
	// corpus is big enough.
	c.templates = max(n/1000, 16)
	c.hosts = max(n/50, 4)
	return c
}

// Name is the artifact name, e.g. fixture-v1-10m.
func (c *Corpus) Name() string {
	switch {
	case c.N >= 1_000_000 && c.N%1_000_000 == 0:
		return fmt.Sprintf("fixture-v%d-%dm", Version, c.N/1_000_000)
	case c.N >= 1_000 && c.N%1_000 == 0:
		return fmt.Sprintf("fixture-v%d-%dk", Version, c.N/1_000)
	default:
		return fmt.Sprintf("fixture-v%d-%d", Version, c.N)
	}
}

// rng returns the deterministic stream for one (docid, purpose) pair.
// Purposes keep the draws independent so adding a draw to one column
// never shifts another.
func (c *Corpus) rng(docid uint64, purpose uint64) *rand.Rand {
	return rand.New(rand.NewSource(int64(splitmix(c.Seed ^ splitmix(docid*2+purpose)))))
}

const (
	purText  = 0
	purLinks = 1
	purMeta  = 2
	purTmpl  = 3
)

// Page generates docid's row. Rows come back in fetch order because
// FetchMS increases with docid.
func (c *Corpus) Page(docid uint64) Page {
	if docid >= c.N {
		panic("fixture: docid out of range")
	}
	meta := c.rng(docid, purMeta)

	p := Page{Docid: docid}
	host := powerLawIndex(meta, c.hosts)
	p.URL = fmt.Sprintf("https://h%d.fixture.chizu/p%d", host, docid)

	// Template membership decides where the text comes from.
	tmpl := int64(-1)
	if meta.Intn(100) < templateShare {
		tmpl = int64(powerLawIndex(meta, c.templates))
	}
	cjk := meta.Intn(100) < cjkShare
	if tmpl >= 0 {
		// The template owns its language; members drawing their own
		// would render the shared stream two ways and break the
		// near-dup shape.
		cjk = splitmix(c.Seed^splitmix(uint64(tmpl)+0xCE))%100 < cjkShare
	}

	if tmpl >= 0 {
		// Members share the template's token stream; a member-specific
		// token every mutationEvery keeps them near-dups, not dups.
		p.Title, p.Text = c.templateText(uint64(tmpl), docid, cjk)
		p.Template = tmpl
	} else {
		p.Template = -1
		p.Title, p.Text = c.freshText(docid, cjk)
	}
	if cjk {
		p.Lang = 2
	} else {
		p.Lang = 1
	}

	p.Outlinks = c.links(docid)

	p.FetchMS = fetchBase + docid
	p.Status = 200
	p.SHA256 = sha256.Sum256([]byte(p.Text))
	p.URLFP = urlfp(p.URL)
	p.Simhash = simhash(p.Text)
	p.CanonFP = p.URLFP
	if tmpl < 0 && meta.Intn(100) < canonShare {
		// An explicit canonical to some earlier doc, the crawl-time
		// rel=canonical shape.
		target := uint64(0)
		if docid > 0 {
			target = uint64(meta.Int63n(int64(docid)))
		}
		p.CanonFP = urlfp(c.URL(target))
	}
	return p
}

// URL reconstructs a docid's URL without generating its page, which is
// what link targets need.
func (c *Corpus) URL(docid uint64) string {
	meta := c.rng(docid, purMeta)
	return fmt.Sprintf("https://h%d.fixture.chizu/p%d", powerLawIndex(meta, c.hosts), docid)
}

// Page is one generated document plus the fixture-only fields tests and
// suites assert on (Template, Docid); ToRow drops down to the cold
// format's fifteen columns.
type Page struct {
	Docid    uint64
	URL      string
	URLFP    [16]byte
	FetchMS  uint64
	Status   uint16
	SHA256   [32]byte
	Simhash  uint64
	Lang     byte
	CanonFP  [16]byte
	Title    string
	Text     string
	Outlinks []Outlink
	Template int64 // -1 when not a template member
}

// Outlink mirrors coldfmt.Outlink without importing it here; the writer
// converts.
type Outlink struct {
	DstFP  [16]byte
	Anchor string
}

// freshText draws title and body from the Zipf core plus the unique
// tail (doc 05: ~40% of a web vocabulary is df <= 4, which the tail ids
// supply).
func (c *Corpus) freshText(docid uint64, cjk bool) (title, text string) {
	r := c.rng(docid, purText)
	return c.composeText(r, docid, cjk)
}

// templateText draws the template's stream, then splices member tokens
// so cluster members hash near each other, not onto each other.
func (c *Corpus) templateText(tmpl, docid uint64, cjk bool) (title, text string) {
	r := c.rng(tmpl, purTmpl)
	title, text = c.composeText(r, tmpl, cjk)
	member := c.rng(docid, purText)
	return title, spliceMemberTokens(text, member, docid)
}

// composeText builds one document's title and body.
func (c *Corpus) composeText(r *rand.Rand, id uint64, cjk bool) (title, text string) {
	z := rand.NewZipf(r, zipfS, 1, c.coreVocab-1)

	titleLen := 2 + r.Intn(7)
	bodyLen := bodyLength(r)

	var b []byte
	for i := range titleLen {
		if i > 0 {
			b = append(b, ' ')
		}
		b = appendTerm(b, z.Uint64(), cjk)
	}
	title = string(b)

	// The unique tail: about half of all docs carry one id term that
	// exists nowhere else, repeated 1-2 times.
	tail := ""
	if r.Intn(2) == 0 {
		tail = tailTerm(c.Seed, id)
	}

	b = b[:0]
	sentence := 0
	for i := range bodyLen {
		if i > 0 {
			if sentence >= 8+r.Intn(12) {
				b = append(b, '.', ' ')
				sentence = 0
			} else {
				b = append(b, ' ')
			}
		}
		if tail != "" && (i == bodyLen/3 || (i == 2*bodyLen/3 && r.Intn(2) == 0)) {
			b = append(b, tail...)
		} else {
			b = appendTerm(b, z.Uint64(), cjk)
		}
		sentence++
	}
	return title, string(b)
}

// links draws a power-law out-degree and preferentially attached
// targets: doc 0 is the megahub the anchor-join lab needs.
func (c *Corpus) links(docid uint64) []Outlink {
	r := c.rng(docid, purLinks)
	deg := outDegree(r)
	out := make([]Outlink, 0, deg)
	for range deg {
		target := powerLawIndex(r, c.N)
		if target == docid {
			continue
		}
		out = append(out, Outlink{DstFP: urlfp(c.URL(target)), Anchor: c.anchorText(r)})
	}
	return out
}

// anchorText is a few power-law tokens. This milestone's pipeline is
// strings-only (doc 11: no anchors at C1a), so anchors need Zipf shape
// for the C2 anchor-join lab, not target-title correlation; correlation
// arrives with the C2 corpus work if the ranking suites need it.
func (c *Corpus) anchorText(r *rand.Rand) string {
	n := 1 + r.Intn(3)
	var b []byte
	for i := range n {
		if i > 0 {
			b = append(b, ' ')
		}
		b = appendTerm(b, powerLawIndex(r, c.coreVocab), false)
	}
	return string(b)
}

// bodyLength is log-normal-ish around the web average: exp(N(5.7,0.7))
// clamped to [40, 4000] tokens lands the mean near 400.
func bodyLength(r *rand.Rand) int {
	l := int(math.Exp(5.7 + 0.7*r.NormFloat64()))
	return min(max(l, 40), 4000)
}

// outDegree is a bounded Pareto on [4, 300] with alpha ~1.6; web pages
// average around ten kept outlinks with a heavy tail.
func outDegree(r *rand.Rand) int {
	u := r.Float64()
	d := int(4 * math.Pow(1/(1-u*(1-math.Pow(4.0/300, 1.6))), 1/1.6))
	return min(max(d, 4), 300)
}

// powerLawIndex draws index in [0, n) with P(i) ~ 1/(i+1): index 0 is
// the head. Inverse-CDF of the s=1 Zipf, cheap and monotone.
func powerLawIndex(r *rand.Rand, n uint64) uint64 {
	i := uint64(math.Pow(float64(n), r.Float64())) - 1
	if i >= n {
		i = n - 1
	}
	return i
}

func urlfp(url string) [16]byte {
	s := sha256.Sum256([]byte(url))
	var fp [16]byte
	copy(fp[:], s[:16])
	return fp
}

// splitmix is splitmix64's finalizer, the stream-key mixer.
func splitmix(x uint64) uint64 {
	x += 0x9E3779B97F4A7C15
	x = (x ^ (x >> 30)) * 0xBF58476D1CE4E5B9
	x = (x ^ (x >> 27)) * 0x94D049BB133111EB
	return x ^ (x >> 31)
}
