package fixture

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"math/bits"
	"strings"
	"sync"
	"testing"
	"unicode"

	"github.com/tamnd/chizu/coldfmt"
)

// goldenHash pins the generator's bytes for (Version 1, seed 2107, N
// 100k, first 1000 pages). Any diff here means generated bytes changed:
// bump Version, rename the artifacts, and re-pin.
const goldenHash = "be8a70195a19c5554d49df27ade78f1ad5efe959725166fabc5b68b81d9bb2a5"

func corpusDigest(c *Corpus, n uint64) string {
	h := sha256.New()
	var num [8]byte
	for docid := range n {
		p := c.Page(docid)
		binary.LittleEndian.PutUint64(num[:], p.FetchMS)
		h.Write(num[:])
		h.Write(p.URLFP[:])
		h.Write(p.SHA256[:])
		binary.LittleEndian.PutUint64(num[:], p.Simhash)
		h.Write(num[:])
		h.Write([]byte{p.Lang})
		h.Write(p.CanonFP[:])
		h.Write([]byte(p.Title))
		h.Write([]byte(p.Text))
		for _, l := range p.Outlinks {
			h.Write(l.DstFP[:])
			h.Write([]byte(l.Anchor))
		}
	}
	return hex.EncodeToString(h.Sum(nil))
}

func TestGoldenHash(t *testing.T) {
	got := corpusDigest(New(2107, 100_000), 1000)
	if got != goldenHash {
		t.Fatalf("generator bytes changed: digest %s, golden %s; bump Version and re-pin", got, goldenHash)
	}
}

func TestDeterministicAcrossInstances(t *testing.T) {
	a, b := New(2107, 1_000_000), New(2107, 1_000_000)
	for _, docid := range []uint64{0, 1, 63, 4096, 999_999} {
		pa, pb := a.Page(docid), b.Page(docid)
		if pa.Text != pb.Text || pa.Title != pb.Title || pa.URL != pb.URL || pa.Simhash != pb.Simhash || len(pa.Outlinks) != len(pb.Outlinks) {
			t.Fatalf("doc %d differs across instances", docid)
		}
		if a.URL(docid) != pa.URL {
			t.Fatalf("doc %d: URL() %q != Page().URL %q", docid, a.URL(docid), pa.URL)
		}
	}
}

// The sample corpus most distribution tests share, generated once; it
// is pure output, so sharing it across tests changes nothing.
const sampleN = 20_000

var sampleOnce = sync.OnceValues(func() (*Corpus, []Page) {
	c := New(2107, sampleN)
	pages := make([]Page, sampleN)
	for i := range pages {
		pages[i] = c.Page(uint64(i))
	}
	return c, pages
})

func samplePages(t *testing.T) (*Corpus, []Page) {
	t.Helper()
	return sampleOnce()
}

func TestZipfTermShape(t *testing.T) {
	_, pages := samplePages(t)
	df := map[string]int{}
	tf := map[string]int{}
	total := 0
	for _, p := range pages {
		seen := map[string]bool{}
		for tok := range strings.FieldsSeq(p.Text) {
			tok = strings.TrimSuffix(tok, ".")
			tf[tok]++
			total++
			if !seen[tok] {
				seen[tok] = true
				df[tok]++
			}
		}
	}

	// Head heaviness: the top term should carry percents of the token
	// mass, Zipf's signature.
	top := 0
	for _, n := range tf {
		if n > top {
			top = n
		}
	}
	if frac := float64(top) / float64(total); frac < 0.02 || frac > 0.25 {
		t.Fatalf("top term carries %.3f of tokens; expected Zipf-like 0.02-0.25", frac)
	}

	// Tail mass: the doc 05 arithmetic leans on ~40% of terms being
	// df <= 4; the generator should land in that neighborhood or above.
	small := 0
	for _, n := range df {
		if n <= 4 {
			small++
		}
	}
	if frac := float64(small) / float64(len(df)); frac < 0.30 {
		t.Fatalf("df<=4 terms are %.3f of vocabulary; want >= 0.30", frac)
	}
	t.Logf("vocab %d terms, %d tokens, top-term share %.3f, df<=4 share %.3f",
		len(df), total, float64(top)/float64(total), float64(small)/float64(len(df)))
}

func TestLinkPowerLaw(t *testing.T) {
	c, pages := samplePages(t)
	indeg := map[[16]byte]int{}
	sum, maxDeg := 0, 0
	for _, p := range pages {
		sum += len(p.Outlinks)
		if len(p.Outlinks) > maxDeg {
			maxDeg = len(p.Outlinks)
		}
		for _, l := range p.Outlinks {
			indeg[l.DstFP]++
		}
	}
	mean := float64(sum) / float64(len(pages))
	if mean < 4 || mean > 60 {
		t.Fatalf("mean out-degree %.2f outside [4, 60]", mean)
	}
	if maxDeg < 30 {
		t.Fatalf("max out-degree %d; power law should reach past 30", maxDeg)
	}
	// Preferential attachment: doc 0 is the megahub.
	hub := indeg[urlfp(c.URL(0))]
	mid := indeg[urlfp(c.URL(sampleN/2))]
	if hub < 100 || hub < 20*max(mid, 1) {
		t.Fatalf("doc 0 in-degree %d, mid doc %d; hub skew missing", hub, mid)
	}
	t.Logf("mean out %.1f, max out %d, hub in-degree %d, mid in-degree %d", mean, maxDeg, hub, mid)
}

func TestNearDupClusters(t *testing.T) {
	_, pages := samplePages(t)
	byTemplate := map[int64][]int{}
	for i, p := range pages {
		if p.Template >= 0 {
			byTemplate[p.Template] = append(byTemplate[p.Template], i)
		}
	}
	if len(byTemplate) == 0 {
		t.Fatal("no template clusters generated")
	}

	members := 0
	biggest := 0
	for _, m := range byTemplate {
		members += len(m)
		if len(m) > biggest {
			biggest = len(m)
		}
	}
	if frac := float64(members) / float64(len(pages)); frac < 0.05 || frac > 0.20 {
		t.Fatalf("template members are %.3f of corpus; want ~0.10", frac)
	}
	if biggest < 3*members/len(byTemplate) {
		t.Fatalf("biggest cluster %d not degenerate against avg %d", biggest, members/len(byTemplate))
	}

	// Members of one cluster are near-dups: simhash within a few bits.
	// Non-members are far.
	checked := 0
	for _, m := range byTemplate {
		if len(m) < 2 {
			continue
		}
		a, b := pages[m[0]], pages[m[1]]
		if d := bits.OnesCount64(a.Simhash ^ b.Simhash); d > 12 {
			t.Fatalf("cluster members %d and %d hamming %d; near-dup shape broken", a.Docid, b.Docid, d)
		}
		if a.Text == b.Text {
			t.Fatalf("cluster members %d and %d are exact dups; splice missing", a.Docid, b.Docid)
		}
		checked++
		if checked >= 20 {
			break
		}
	}
	if checked == 0 {
		t.Fatal("no multi-member cluster in sample")
	}
	far := bits.OnesCount64(pages[3].Simhash ^ pages[4].Simhash)
	if pages[3].Template == -1 && pages[4].Template == -1 && far < 10 {
		t.Fatalf("unrelated docs hamming %d; simhash degenerate", far)
	}
	t.Logf("%d clusters, %d members, biggest %d", len(byTemplate), members, biggest)
}

func TestCJKDocs(t *testing.T) {
	_, pages := samplePages(t)
	cjk := 0
	for _, p := range pages {
		if p.Lang != 2 {
			continue
		}
		cjk++
		for _, r := range p.Title {
			if r != ' ' && !unicode.Is(unicode.Han, r) {
				t.Fatalf("doc %d lang 2 title has non-Han rune %q", p.Docid, r)
			}
		}
	}
	if frac := float64(cjk) / float64(len(pages)); frac < 0.02 || frac > 0.10 {
		t.Fatalf("CJK docs are %.3f of corpus; want ~0.05", frac)
	}
}

func TestTermSpellingDisjointAndUnique(t *testing.T) {
	seen := map[string]uint64{}
	for rank := range uint64(200_000) {
		term := string(appendTerm(nil, rank, false))
		if prev, dup := seen[term]; dup {
			t.Fatalf("ranks %d and %d both spell %q", prev, rank, term)
		}
		seen[term] = rank
		if len(term) == 0 || len(term) > 64 {
			t.Fatalf("rank %d spells %d bytes", rank, len(term))
		}
	}
}

func TestSegmentsRoundTrip(t *testing.T) {
	c := New(2107, 500)
	var segs [][]byte
	err := c.Segments(0xC0FFEE, 200, func(seq uint64, seg []byte) error {
		if seq != uint64(len(segs)+1) {
			return fmt.Errorf("seq %d out of order", seq)
		}
		segs = append(segs, bytes.Clone(seg))
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(segs) != 3 {
		t.Fatalf("500 rows at 200/seg gave %d segments", len(segs))
	}
	docid := uint64(0)
	for _, seg := range segs {
		ps, err := coldfmt.OpenPageSegment(seg)
		if err != nil {
			t.Fatal(err)
		}
		rows, err := ps.Rows()
		ps.Close()
		if err != nil {
			t.Fatal(err)
		}
		for _, row := range rows {
			p := c.Page(docid)
			want := ToRow(&p)
			if row.URL != want.URL || row.Text != want.Text || row.Simhash != want.Simhash ||
				row.FetchMS != want.FetchMS || len(row.Outlinks) != len(want.Outlinks) {
				t.Fatalf("doc %d round-trip mismatch", docid)
			}
			docid++
		}
	}
	if docid != 500 {
		t.Fatalf("read back %d rows", docid)
	}
}
